//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: /Users/lizynz/Desktop/Payload/TikTok.app/Frameworks/BDLRepairer.framework/BDLRepairer
// UUID: C8F2072B-E480-3273-8762-B4919D125A16
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//            Minimum iOS version: 9.0.0
//                    SDK version: 14.5.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @executable_path/Frameworks
//                               = /Users/lizynz/Desktop/Payload/TikTok.app/Frameworks/BDLRepairer.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = /Users/lizynz/Desktop/Payload/TikTok.app/Frameworks/BDLRepairer.framework/Frameworks
//

@interface NSObject (BDLMusicallyCoreRepairer)
+ (void)load;
+ (void)initialize;
@end

