//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: /Users/lizynz/Desktop/Payload/TikTok.app/Frameworks/libvcn.framework/libvcn
// UUID: CDC805BC-8B1B-3471-AA70-1543AC6E510D
//
//                           Arch: arm64
//                Current version: 0.0.0
//          Compatibility version: 0.0.0
//                 Source version: 0.0.0.0.0
//            Minimum iOS version: 8.0.0
//                    SDK version: 14.3.0
//

//
// This file does not contain any Objective-C runtime information.
//
