//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: /Users/lizynz/Desktop/Payload/TikTok.app/Frameworks/TTFFmpeg.framework/TTFFmpeg
// UUID: D4EC55D2-DB77-3B43-93C6-1C8CAC60007A
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//            Minimum iOS version: 9.0.0
//                    SDK version: 14.3.0
//
//                       Run path: @executable_path/Frameworks
//                               = /Users/lizynz/Desktop/Payload/TikTok.app/Frameworks/TTFFmpeg.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = /Users/lizynz/Desktop/Payload/TikTok.app/Frameworks/TTFFmpeg.framework/Frameworks
//

//
// This file does not contain any Objective-C runtime information.
//
