//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: AAWEBootChecker
// UUID: 6E039FE4-FE34-368A-9C30-0CB77A8603D7
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//            Minimum iOS version: 9.0.0
//                    SDK version: 14.1.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @executable_path/Frameworks
//                               = /Frameworks
//                       Run path: @loader_path/Frameworks
//                               = /Frameworks
//

@interface AAWEBootChecker : NSObject
{
}

+ (_Bool)shouldCheckTargetPath:(id)arg1;
+ (void)load;

@end

@interface AAWEBootStub : NSObject
{
}

+ (void)load;

@end

@interface AAWEBootStub (cat)
+ (void)load;
@end

