//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Named Structures

struct CGSize {
    double _field1;
    double _field2;
};

#pragma mark -

//
// File: TikTokMSearchFramework
// UUID: 6BA7121A-292A-30E0-ACB8-5D71E0680480
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//            Minimum iOS version: 10.0.0
//                    SDK version: 15.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @executable_path/Frameworks
//                               = /Frameworks
//

@protocol AMSearchRateProtocol
@end

@protocol AWEAVPlayerWrapperDelegate
@end

@protocol AWEAdSearchOperationGuideView
@end

@protocol AWEAdTracker
@end

@protocol AWEAdUtility
@end

@protocol AWEAppAwemeSettingMessage
@end

@protocol AWEAppDarkForestSettingManager
@end

@protocol AWEAweDoubleColumnDynamicCoverProtocol
@end

@protocol AWEAwemeDeletionMessage
@end

@protocol AWEAwemeDetailTableViewControllerDelegate
@end

@protocol AWEAwemeDetailTableViewControllerProtocol
@end

@protocol AWEAwemeDetailViewControllerProtocol
@end

@protocol AWEAwemePlayVideoControllerProtocol
@end

@protocol AWEAwemePlayVideoDelegate
@end

@protocol AWECommonConfig
@end

@protocol AWECrotocol
@end

@protocol AWEDiscoverBundleService
@end

@protocol AWEDoubleColumnRecomMenuDelegate
@end

@protocol AWEDynamicCoverManager
@end

@protocol AWEDynamicCoverStrategyProtocol
@end

@protocol AWEFTCChildModelModuleService
@end

@protocol AWEFeedCollectionViewControllerProtocol
@end

@protocol AWEFeedModuleService
@end

@protocol AWEFeedNearbyCollectionCellProtocol
@end

@protocol AWEGeneralSearchChunkControllerDelegate
@end

@protocol AWEGeneralSearchRecomMenuDelegate
@end

@protocol AWEHashTag2EmojiService
@end

@protocol AWEHybridAudioPlayerManagerDelegate
@end

@protocol AWEIMModuleService
@end

@protocol AWEInputTextCutManager
@end

@protocol AWEIrregularWordProtocol <NSObject>
- (NSString *)getDisplayWord;

@optional
@property(copy, nonatomic) NSAttributedString *pureTextContent;
- (NSString *)getQueryType;
- (unsigned long long)getTagType;
- (double)getTagPadding;
- (long long)getRankPosition;
- (NSString *)getWordID;
- (NSString *)getSearchWord;
@end

@protocol AWEIrregularWordsViewControllerProtocol
@end

@protocol AWELiveCollectionProtocol
@end

@protocol AWELiveModuleService
@end

@protocol AWEModernFullscreenTransitionInnerContextProvider
@end

@protocol AWEModernFullscreenTransitionOuterContextProvider
@end

@protocol AWENewCollectionDelegateWaterfallLayout
@end

@protocol AWEPlayVideoProgressDelegate
@end

@protocol AWEPreviewable
@end

@protocol AWERegularWordProtocol <NSObject>
- (NSString *)getContentString;

@optional
- (NSString *)getImageURL;
- (NSString *)getWordID;
- (NSString *)getDisplayWord;
- (long long)defaultStyle;
@end

@protocol AWEReportModuleService
@end

@protocol AWERouterViewControllerProtocol
@end

@protocol AWESearchActionListenerProtocol
@end

@protocol AWESearchBundleService
@end

@protocol AWESearchChildViewControllerProtocol
@end

@protocol AWESearchChildViewEventTrackDataProtocol
@end

@protocol AWESearchDynamicTableViewCellDelegate
@end

@protocol AWESearchFIlmTVEpisodeSheetProtocol
@end

@protocol AWESearchFilmTVEpisodesProtocol
@end

@protocol AWESearchFilmTVTagViewProtocol
@end

@protocol AWESearchGeneralFlowChunkDataReceiver
@end

@protocol AWESearchLynxEngineDelegate
@end

@protocol AWESearchMiddleProtocol
@end

@protocol AWESearchMiddleViewControllerProtocol
@end

@protocol AWESearchMultiFeedFallThroughProtocol
@end

@protocol AWESearchPlaceholderProtocol
@end

@protocol AWESearchRelatedSearchCellDelegate
@end

@protocol AWESearchResultViewControllerDelegate
@end

@protocol AWESearchSugTableViewCellDelegate
@end

@protocol AWESearchSugViewControllerProtocol
@end

@protocol AWESearchTopUserContentCellProtocol
@end

@protocol AWEShareActivity
@end

@protocol AWEShareAweme
@end

@protocol AWEShareChallenge
@end

@protocol AWEShareComment
@end

@protocol AWEShareECommerce
@end

@protocol AWEShareFactory
@end

@protocol AWEShareGame
@end

@protocol AWEShareGroup
@end

@protocol AWEShareLive
@end

@protocol AWEShareLiveEvent
@end

@protocol AWEShareLuckyCat
@end

@protocol AWEShareMusic
@end

@protocol AWEShareMusicList
@end

@protocol AWESharePlayList
@end

@protocol AWEShareQRCode
@end

@protocol AWEShareQuestion
@end

@protocol AWEShareSearch
@end

@protocol AWEShareService
@end

@protocol AWEShareSettings
@end

@protocol AWEShareSticker
@end

@protocol AWEShareSubscribeInvitation
@end

@protocol AWEShareTracking
@end

@protocol AWEShareUser
@end

@protocol AWEShareUtility
@end

@protocol AWEShareWeb
@end

@protocol AWESlidingViewControllerDelegate
@end

@protocol AWEStudioAlbumExternalService
@end

@protocol AWEStudioCapabilities
@end

@protocol AWEStudioChallengeExternalService
@end

@protocol AWEStudioClipExternalService
@end

@protocol AWEStudioCreatorPreviewExternalService
@end

@protocol AWEStudioDraftExternalService
@end

@protocol AWEStudioDuetExternalService
@end

@protocol AWEStudioECLibraryExternalService
@end

@protocol AWEStudioEditExternalService
@end

@protocol AWEStudioJSBridgeExternalService
@end

@protocol AWEStudioMVExternalService
@end

@protocol AWEStudioModuleService
@end

@protocol AWEStudioMusicExternalService
@end

@protocol AWEStudioPublishExternalService
@end

@protocol AWEStudioPushExternalService
@end

@protocol AWEStudioRecordExternalService
@end

@protocol AWEStudioRouterExternalService
@end

@protocol AWEStudioStickerExternalService
@end

@protocol AWEStudioStitchExternalService
@end

@protocol AWEStudioTaskExternalService
@end

@protocol AWETransitionContextProvider
@end

@protocol AWEUILoadingSearchProtocol <NSObject>
+ (void)dismissSearchLoadingWithAnimated:(_Bool)arg1;
+ (void)dismissSearchLoading;
+ (AWEUILoadingView *)showSearchLoadingWithBackground:(_Bool)arg1;
@end

@protocol AWEUserDetailViewControllerProtocol
@end

@protocol AWEUserMessage
@end

@protocol AWEUserProfileModuleService
@end

@protocol AWEUserRecommendModuleService
@end

@protocol AWEUserRelationService
@end

@protocol AWEUserService
@end

@protocol AWEWebImageTransformProtocol
@end

@protocol AWEZoomTransitionOuterContextProvider
@end

@protocol BCAABundleActivator
@end

@protocol BCAABundleService
@end

@protocol BCAAInstanceService
@end

@protocol BDLynxViewDelegate
@end

@protocol BDLynxViewUIDelegate
@end

@protocol BDXContainerLifecycleProtocol
@end

@protocol BDXLynxElement
@end

@protocol BDXResourceLoaderProtocol
@end

@protocol BDXServiceProtocol
@end

@protocol BDXViewContainerServiceProtocol
@end

@protocol HTSService
@end

@protocol HTSServiceUnavailable
@end

@protocol IESLiveNewPlayerControllerDelegate
@end

@protocol IESLiveNewPlayerControllerReuseDelegate
@end

@protocol IESVideoPlayerDelegate
@end

@protocol IGListAdapterDataSource
@end

@protocol IGListAdapterDelegate
@end

@protocol IGListDiffable
- (_Bool)isEqualToDiffableObject:(id <IGListDiffable>)arg1;
- (id <NSObject>)diffIdentifier;
@end

@protocol IGListSingleSectionControllerDelegate
@end

@protocol IGListSupplementaryViewSource <NSObject>
- (struct CGSize)sizeForSupplementaryViewOfKind:(NSString *)arg1 atIndex:(long long)arg2;
- (UICollectionReusableView *)viewForSupplementaryElementOfKind:(NSString *)arg1 atIndex:(long long)arg2;
- (NSArray *)supportedElementKinds;
@end

@protocol LynxTimingListener
@end

@protocol LynxViewLifecycle
@end

@protocol MTLJSONSerializing
@end

@protocol MTLModel
@end

@protocol MTLTransformerErrorHandling
@end

@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)arg1;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (_Bool)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol SparkContainerLifecycleProtocol
@end

@protocol TTKCommercePlayVideoInteractionDelegate
@end

@protocol TTKCommerceVideoPlayerController
@end

@protocol TTKFeedPlayerCaptionDelegate
@end

@protocol TTKFeedPlayerCaptionProtocol
@end

@protocol TTKFeedPlayerControlProtocol
@end

@protocol TTKFeedPlayerControllerProtocol
@end

@protocol TTKFeedPlayerDelegate
@end

@protocol TTKFeedPlayerLegacyProtocol
@end

@protocol TTKFeedPlayerLoadDelegate
@end

@protocol TTKFeedPlayerPlaybackStateDelegate
@end

@protocol TTKFeedPlayerProtocol
@end

@protocol TTKFeedPlayerStatusProtocol
@end

@protocol TTKFeedPlayerTimeObserverProtocol
@end

@protocol TTKFeedTrendingInflowDataProtocol
@end

@protocol TTKFeedbackViewDelegate
@end

@protocol TTKOtherFeedbackViewDelegate
@end

@protocol TTKPoplayerProtocol
@end

@protocol TTKSearchAdViewControllerDelegate
@end

@protocol TTKSearchAudioPlayerServiceProtocol
@end

@protocol TTKSearchBulletContainerDelegate
@end

@protocol TTKSearchCardViewProtocol
@end

@protocol TTKSearchCommonCollectionViewCellDelegate
@end

@protocol TTKSearchContaienrServiceProtocol
@end

@protocol TTKSearchContainerAutoPlayServiceProtocol
@end

@protocol TTKSearchContainerListServiceProtocol
@end

@protocol TTKSearchContainerSectionControllerDelegate
@end

@protocol TTKSearchContainerThemeServiceProtocol
@end

@protocol TTKSearchContainerTrackerServiceProtocol
@end

@protocol TTKSearchContainerTransitionServiceProtocol
@end

@protocol TTKSearchDynamicTableViewCellProtocol
@end

@protocol TTKSearchHorizontalDelegate
@end

@protocol TTKSearchHorizontalViewCellProtocol
@end

@protocol TTKSearchLearnMoreViewContainer
@end

@protocol TTKSearchLynxContainerDataSourceProtocol
@end

@protocol TTKSearchLynxElementStatusDelegate
@end

@protocol TTKSearchLynxElementViewProtocol
@end

@protocol TTKSearchLynxLiveViewPlayerDelegate
@end

@protocol TTKSearchMessageDeliverer
@end

@protocol TTKSearchMessageHandler
@end

@protocol TTKSearchQueryListManager
@end

@protocol TTKSearchSparkCollectionViewCellDelegate
@end

@protocol TTKSearchSparkContainerDelegate
@end

@protocol TTKSearchThemeColorProvider
@end

@protocol TTKSearchUserSuggestionElement
@end

@protocol TTKSearchVideoCollectionViewCellDelegate
@end

@protocol TTKSearchVideoViewPlayerDelegate
@end

@protocol TTKStudioGreenScreenKitExternalService
@end

@protocol TTKStudioStickerCapability
@end

@protocol TTKUIAdaptivityService
@end

@protocol TikTokBizBridgeModuleService
@end

@protocol TikTokCommentModuleService
@end

@protocol TikTokECommerceModuleService
@end

@protocol TikTokFeedAwemeService
@end

@protocol TikTokInlayScrollPanelActionDelegate
@end

@protocol TikTokInlayScrollPanelContentView
@end

@protocol TikTokInlayScrollPanelTopView
@end

@protocol TikTokInviteSearchTableViewCellProtocol
@end

@protocol TikTokLynxKitModuleService
@end

@protocol TikTokPlayListMessage
@end

@protocol TikTokPlayListModuleService
@end

@protocol TikTokPlaylistDataManagerObserver
@end

@protocol TikTokSearchAladdinVideoListDataSourceHolder <NSObject>
@property(retain, nonatomic) TikTokSearchVideoListSyncDataController *awe_syncDataController;
@end

@protocol TikTokSearchAladdinVideoListProtocol
@end

@protocol TikTokSearchAutoPlayCardProtocol
@end

@protocol TikTokSearchAutoPlayContainerProtocol
@end

@protocol TikTokSearchAutoPlayHotZoneRule
@end

@protocol TikTokSearchDynamicSectionControllerDelegate
@end

@protocol TikTokSearchDynamicTableViewCellDelegate
@end

@protocol TikTokSearchEntryService
@end

@protocol TikTokSearchGuideSearchComponentContextProvider
@end

@protocol TikTokSearchGuideSearchComponentDelegate
@end

@protocol TikTokSearchGuideSearchViewActionDelegate
@end

@protocol TikTokSearchGuideSearchViewDataSource
@end

@protocol TikTokSearchHorizontalAutoPlayCellProtocol
@end

@protocol TikTokSearchHorizontalAutoPlayViewDelegate
@end

@protocol TikTokSearchHotSpotBottomViewDelegate
@end

@protocol TikTokSearchPlaceholderCellDelegate
@end

@protocol TikTokSearchPlaceholderDataSource
@end

@protocol TikTokSearchPlaceholderDelegate
@end

@protocol TikTokSearchPlaylistDataManagerDelegate
@end

@protocol TikTokSearchResultCorrectListener
@end

@protocol TikTokSearchResultStickyComponentViewModel
@end

@protocol TikTokSearchSortAndFilterButton
@end

@protocol TikTokSearchSortAndFilterPanelFeedbackViewActionDelegate
@end

@protocol TikTokSearchSortAndFilterPanelTopViewActionDelegate
@end

@protocol TikTokSearchSortAndFilterTableViewDataSource
@end

@protocol TikTokSearchSortAndFilterTableViewDelegate
@end

@protocol TikTokSearchSortAndFilterTrackerContextProvider
@end

@protocol TikTokSearchSortAndFilterViewController
@end

@protocol TikTokSearchSortAndFilterViewControllerDelegate
@end

@protocol TikTokSearchUserManagerProtocol
@end

@protocol TikTokSettingsModuleService
@end

@protocol TikTokTabBarModuleService
@end

@protocol UIAdaptivePresentationControllerDelegate
@end

@protocol UIBarPositioningDelegate
@end

@protocol UICollectionViewDataSource
@end

@protocol UICollectionViewDelegate
@end

@protocol UICollectionViewDelegateFlowLayout
@end

@protocol UIGestureRecognizerDelegate
@end

@protocol UIPopoverPresentationControllerDelegate
@end

@protocol UIScrollViewDelegate
@end

@protocol UISearchBarDelegate
@end

@protocol UITableViewDataSource
@end

@protocol UITableViewDelegate
@end

@protocol UIViewControllerAnimatedTransitioning
@end

@protocol UIViewControllerTransitioningDelegate
@end

@protocol YYTextViewDelegate
@end

@interface BDLDecompressor_TikTokMSearchFramework : NSObject <NSCopying>
{
    int _foo;
}

+ (void)load;
+ (double)getDecompressFixSelTime;
+ (double)getDecompressAllTime;
@property(nonatomic) int foo; // @synthesize foo=_foo;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

@interface BCAABundleContextPlaceholder : NSObject
{
}

@end

@interface PodsDummy_Pods_TikTokMSearchFramework : NSObject
{
}

@end

@interface AWEAppSearchSettingManager : NSObject
{
}

@end

@interface AWEConcernUsersCardDataController : NSObject
{
}

@end

@interface AWEDoubleColumnDynamicCardViewModel : NSObject
{
}

@end

@interface AWEDoubleColumnGeneralDivideLineViewModel : NSObject
{
}

@end

@interface AWEDoubleColumnGeneralSearchCommonCell : UICollectionViewCell
{
}

@end

@interface AWEDoubleColumnGeneralSearchCommonCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWEDoubleColumnGeneralSearchMoreViewCell : UICollectionViewCell
{
}

@end

@interface AWEDoubleColumnGeneralSearchMoreViewCellApdater : TTKSearchCardAdapter
{
}

@end

@interface AWEDoubleColumnGeneralSearchMoreViewModel : NSObject
{
}

@end

@interface AWEDoubleColumnGeneralSearchViewController : AWESearchBaseViewController
{
}

@end

@interface AWEDoubleColumnGeneralVideoSectionController : IGListSectionController
{
}

@end

@interface AWEDoubleColumnRelatedSearchViewModel : NSObject
{
}

@end

@interface AWEDynamicCoverManager : HTSService
{
}

@end

@interface AWEDynamicCoverStrategyManager : NSObject
{
}

@end

@interface AWEFeedCollectionHeaderView : UICollectionReusableView
{
}

@end

@interface AWEFeedCollectionViewController : UIViewController
{
}

@end

@interface AWEFeedCollectionViewForSearchController : AWEFeedCollectionViewController
{
}

@end

@interface AWEFeedHotTestImageCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWEFeedModuleConfig : NSObject
{
}

@end

@interface AWEFeedSearchVideoAuthorUpCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWEFeedSearchVideoCardCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWEFeedSearchVideoCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWEFeedSearchDoubleColumnVideoCollectionViewCell : AWEFeedSearchVideoCollectionViewCell
{
}

@end

@interface AWEFilmTVEpisodeResponseModel : AWEBaseApiModel
{
}

@end

@interface AWEFilmTVEpisodeDataController : AWEListDataController
{
}

@end

@interface AWEGeneralActivityView : UIView
{
}

@end

@interface AWEGeneralSearchCardDataController : AWEListDataController
{
}

@end

@interface AWEGeneralSearchDataController : AWEListDataController
{
}

@end

@interface AWEGeneralSearchRecomMenuItemView : UIControl
{
}

@end

@interface AWEGeneralSearchRecomMenuView : UIView
{
}

@end

@interface AWEGuessSearchViewController : AWEIrregularWordsBaseViewController
{
}

@end

@interface AWEInviteSearchTableViewCell : AWESearchUserTableViewCell
{
}

@end

@interface AWEIrregularWordsBaseViewController : UIViewController
{
}

@end

@interface AWEModernFeedTikTokVideoFrame : AWEModernFeedCellFrame
{
}

@end

@interface AWEModernFullscreenMagnifyTransition : NSObject
{
}

@end

@interface AWEModernFullscreenShrinkTransition : NSObject
{
}

@end

@interface AWEModernFullscreenInteractiveShrinkTransition : NSObject
{
}

@end

@interface AWEModernFullScreenPopTransition : NSObject
{
}

@end

@interface AWENewHotSearchModel : AWEBaseApiModel
{
}

@end

@interface AWESearchABTestRegister : NSObject
{
}

@end

@interface AWESearchAladdinBaseVideoListView : UIView
{
}

@end

@interface AWESearchAladdinNewVideoListView : AWESearchAladdinBaseVideoListView
{
}

@end

@interface AWESearchAladdinUserMusicListView : UIView
{
}

@end

@interface AWESearchAladdinVideoListFooterView : UICollectionReusableView
{
}

@end

@interface AWESearchAladdinVideoListUpdateModel : NSObject
{
}

@end

@interface AWESearchAladdinVideoListView : AWESearchAladdinBaseVideoListView
{
}

@end

@interface AWESearchAllManager : AWESearchBaseManager
{
}

@end

@interface AWESearchBaseManager : NSObject
{
}

@end

@interface AWESearchBaseViewController : UIViewController
{
}

@end

@interface AWESearchBridgeRegister : NSObject
{
}

@end

@interface AWESearchChallengeManager : AWESearchBaseManager
{
}

@end

@interface AWESearchChallengeTableViewCell : AWEUIListTableViewCell
{
}

@end

@interface AWESearchChallengeViewController : AWESearchBaseViewController
{
}

@end

@interface AWESearchCorrectView : UICollectionReusableView
{
}

@end

@interface AWESearchDictionaryBuilder : NSObject
{
}

@end

@interface AWESearchDynamicCardCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWESearchDynamicTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchFeedAutoPlayManager : NSObject
{
}

@end

@interface AWESearchFeedbackGuideView : UIView
{
}

@end

@interface AWESearchFIlmTVEpisodeSheet : UIView
{
}

@end

@interface AWESearchFilmTVEpisodesView : UIView
{
}

@end

@interface AWESearchFilmTVEpisodesViewController : UIViewController
{
}

@end

@interface AWESearchTagBackgroudImageTransformer : NSObject
{
}

@end

@interface AWESearchFilmTVTagView : UIView
{
}

@end

@interface AWESearchFinitePushController : NSObject
{
}

@end

@interface AWESearchFrequencyManager : NSObject
{
}

@end

@interface AWESearchGeneralFlowChunkDataHelper : NSObject
{
}

@end

@interface AWESearchGradientBackgroundView : UIView
{
}

@end

@interface AWESearchHarmfulCategoryManager : NSObject
{
}

@end

@interface AWESearchHistoryCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWESearchHistoryFlowLayout : UICollectionViewFlowLayout
{
}

@end

@interface AWESearchHistoryReusableHeaderView : UICollectionReusableView
{
}

@end

@interface AWESearchRSImageItemCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWESearchImageRecommendCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWELegacySearchKeyWord : NSString
{
}

@end

@interface AWESearchKeyWordModel : NSString
{
}

@end

@interface AWESearchLandingPagePropsResponseModel : AWEBaseApiModel
{
}

@end

@interface AWESearchLandingPageEffectsListModel : AWEBaseApiModel
{
}

@end

@interface AWESearchLandingPageDataController : AWEListDataController
{
}

@end

@interface AWESearchLandingPageTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchLandingPageViewController : UIViewController
{
}

@end

@interface AWESearchLynxEngine : NSObject
{
}

@end

@interface AWESearchMiddleUtility : NSObject
{
}

@end

@interface AWESearchMiddleViewController : UIViewController
{
}

@end

@interface AWESearchModuleService : NSObject
{
}

@end

@interface AWESearchMonitorHelper : NSObject
{
}

@end

@interface AWESearchMultiFeedFallThroughParams : NSObject
{
}

@end

@interface AWESearchMusicsAuthorCardMoreTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchMusicsAuthorCardTitleTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchMusicsClusterTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchMusicsManager : AWESearchBaseManager
{
}

@end

@interface AWESearchMusicsViewController : AWESearchBaseViewController
{
}

@end

@interface AWESearchMusicTableViewCell : AWEUIListTableViewCell
{
}

@end

@interface AWESearchPlaceholderHistoryTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchPlaceholderHotTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchPlaceholderViewController : UIViewController
{
}

@end

@interface AWESearchRateItemView : UIView
{
}

@end

@interface AWESearchRecommendWordTagView : UIView
{
}

@end

@interface AWESearchRecommendCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWESearchRelatedSearchItemModel : MTLModel
{
}

@end

@interface AWESearchRelatedSearchCellModel : MTLModel
{
}

@end

@interface AWESearchRelatedSearchItemView : UIControl
{
}

@end

@interface AWESearchRelatedSearchCollectionViewCell : UICollectionViewCell
{
}

@end

@interface AWESearchResultViewController : UIViewController
{
}

@end

@interface AWESearchScrollViewTheme : NSObject
{
}

@end

@interface AWESearchStarAlladinVideoCell : UICollectionViewCell
{
}

@end

@interface AWESearchSugManager : NSObject
{
}

@end

@interface AWESearchSugTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchSugViewController : UIViewController
{
}

@end

@interface AWESearchTabConfig : NSObject
{
}

@end

@interface AWESearchTracker : NSObject
{
}

@end

@interface AWESearchTrendBoardEditionModel : AWEBaseApiModel
{
}

@end

@interface AWESearchTrendBoardEditionResponseModel : AWEBaseApiModel
{
}

@end

@interface AWESearchTVEpisodeTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchUserManager : AWESearchBaseManager
{
}

@end

@interface AWESearchUserTableViewCell : AWEUIListTableViewCell
{
}

@end

@interface AWESearchUserViewController : AWESearchBaseViewController
{
}

@end

@interface AWESearchUtility : NSObject
{
}

@end

@interface AWESearchVarietyEpisodeTableViewCell : UITableViewCell
{
}

@end

@interface AWESearchVideoListDataViewController : AWEListDataController
{
}

@end

@interface AWESearchVideoViewController : AWESearchBaseViewController
{
}

@end

@interface AWESearchViewController : UIViewController
{
}

@end

@interface BDXBridgeClickSearchCardMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeClickSearchCardMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeClickSearchCardCardParams : BDXBridgeModel
{
}

@end

@interface BDXBridgeFollowPACheckMethodMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeLoadMoreLiveMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeOpenHotspotMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeOpenHotspotMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeOpenLiveMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeOpenLiveMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeOpenLiveMoreMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeOpenLiveMoreMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeOpenPlaylistMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeOpenPlaylistMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeOpenShortVideoMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeOpenShortVideoMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeOpenSingleFeedbackSheetMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeOpenSingleFeedbackSheetMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeSearchEnterLiveFlowMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeSearchEnterLiveFlowMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeSearchKeywordChangeMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeSearchKeywordChangeMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeSearchLaunchChatMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeSearchLaunchChatMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeShowSearchRSReportPanelMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeShowSearchRSReportPanelMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeUpdateRawDataMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeUpdateRawDataMethodParamModel : BDXBridgeModel
{
}

@end

@interface BDXBridgeUserFollowNoticeMethod : BDXBridgeMethod
{
}

@end

@interface BDXBridgeUserFollowNoticeMethodParamModel : BDXBridgeModel
{
}

@end

@interface TikTokSugWordModel : AWEBaseApiModel
{
}

@end

@interface TikTokClickSugModel : AWEBaseApiModel
{
}

@end

@interface TikTokInlayScrollPanelViewController : UIViewController
{
}

@end

@interface TikTokMutualRelationAvatarsView : UIView
{
}

@end

@interface TikTokSearchAladdinCardLoadmoreResponseModel : AWEBaseApiModel
{
}

@end

@interface TikTokSearchAutoPlayHandler : NSObject
{
}

@end

@interface TikTokSearchAutoPlayManager : NSObject
{
}

@end

@interface TikTokSearchCellInfoHelper : NSObject
{
}

@end

@interface TikTokSearchDynamicPlaceHolderTableViewCell : UITableViewCell
{
}

@end

@interface TikTokSearchDynamicSectionController : IGListSectionController
{
}

@end

@interface TikTokSearchFeedAutoPlayDoubleColumnHotZoneRule : NSObject
{
}

@end

@interface TikTokSearchFeedAutoPlayHotZoneRule : NSObject
{
}

@end

@interface TikTokSearchSelectSectionModel : MTLModel
{
}

@end

@interface TikTokSearchActivityItemModel : MTLModel
{
}

@end

@interface TikTokSearchActivitySectionModel : MTLModel
{
}

@end

@interface TikTokSearchFilterItemModel : MTLModel
{
}

@end

@interface TikTokSearchFilterSectionModel : MTLModel
{
}

@end

@interface TikTokSearchFeedbackSectionModel : NSObject
{
}

@end

@interface TikTokSearchFilterSettingsModel : MTLModel
{
}

@end

@interface TikTokSearchGuideSearchCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TikTokSearchGuideSearchView : UIView
{
}

@end

@interface TikTokSearchGuideSearchViewModel : NSObject
{
}

@end

@interface TikTokSearchHorizontalAutoPlayBaseContentView : UIView
{
}

@end

@interface TikTokSearchHorizontalAutoPlayCell : UICollectionViewCell
{
}

@end

@interface TikTokSearchHorizontalAutoPlayHotSpotContentView : TikTokSearchHorizontalAutoPlayBaseContentView
{
}

@end

@interface RTLUICollectionViewFlowLayout : UICollectionViewFlowLayout
{
}

@end

@interface TikTokSearchHorizontalAutoPlayView : UIView
{
}

@end

@interface TikTokSearchHorizontalScrollTailView : UIView
{
}

@end

@interface TikTokSearchHotSpotAutoPlayCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TikTokSearchHotSpotBottomView : UIView
{
}

@end

@interface TikTokSearchHotSpotTopView : UIView
{
}

@end

@interface PodsDummy_TikTokSearchImpl_Pods_TikTokMSearchFramework : NSObject
{
}

@end

@interface TikTokSearchLiveCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TikTokSearchLiveViewController : AWESearchBaseViewController
{
}

@end

@interface TikTokSearchLiveConfig : NSObject
{
}

@end

@interface TikTokSearchLiveViewModel : NSObject
{
}

@end

@interface TikTokSearchMusicHeaderTableViewCell : UITableViewCell
{
}

@end

@interface TikTokSearchPlaceholderABTestUISettings : NSObject
{
}

@end

@interface TikTokSearchPlaceHolderModel : AWEBaseApiModel
{
}

@end

@interface TikTokSearchPlaceHolderDynamicListModel : AWEBaseApiModel
{
}

@end

@interface TikTokSearchPlaceHolderSettingManager : NSObject
{
}

@end

@interface TikTokSearchPlaceholderViewModel : NSObject
{
}

@end

@interface TikTokSearchPlaylistDataManager : NSObject
{
}

@end

@interface TikTokSearchPreciseAdAutoPlayCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TikTokSearchPreciseAdAutoPlayHotZoneRule : NSObject
{
}

@end

@interface TikTokSearchPreciseAdHorizontalAutoPlayContentView : TikTokSearchHorizontalAutoPlayBaseContentView
{
}

@end

@interface TikTokSearchPreciseAdTopView : UIView
{
}

@end

@interface TikTokSearchResultClickThroughView : UIView
{
}

@end

@interface TikTokSearchResultStickyComponentViewController : UIViewController
{
}

@end

@interface TikTokSearchResultTabRecord : NSObject
{
}

@end

@interface TikTokSearchSelectTableViewSectionHeaderView : UITableViewCell
{
}

@end

@interface TikTokSearchSortAndFilterButton : UIButton
{
}

@end

@interface TikTokSearchSortAndFilterPanelFeedbackOnlyTopView : UIView
{
}

@end

@interface TikTokSearchSortAndFilterPanelTopView : UIView
{
}

@end

@interface TikTokSearchSortAndFilterSettingsManager : NSObject
{
}

@end

@interface TikTokSearchActivityTableViewCell : UITableViewCell
{
}

@end

@interface TikTokSearchSortAndFilterTableViewCell : UITableViewCell
{
}

@end

@interface TikTokSearchShowMoreFilterTableViewCell : UITableViewCell
{
}

@end

@interface TikTokSearchFeedbackTableViewCell : UITableViewCell
{
}

@end

@interface TikTokSearchSortAndFilterTableViewSectionHeaderView : UIView
{
}

@end

@interface TikTokSearchSortAndFilterTableViewSectionFooterView : UIView
{
}

@end

@interface TikTokSearchSortAndFilterTableView : UITableView
{
}

@end

@interface TikTokSearchSortAndFilterViewController : UIViewController
{
}

@end

@interface TikTokSearchSortAndFilterViewModel : NSObject
{
}

@end

@interface TikTokSearchSSHVideoFlowLayoutRowInfo : NSObject
{
}

@end

@interface TikTokSearchSSHVideoFlowLayout : UICollectionViewFlowLayout
{
}

@end

@interface TikTokSearchSugReportHintTableViewCell : UITableViewCell
{
}

@end

@interface TikTokSearchUserVideoListAutoPlayContentView : TikTokSearchHorizontalAutoPlayBaseContentView
{
}

@end

@interface TikTokSearchVideoListSyncDataResponseModel : NSObject
{
}

@end

@interface TikTokSearchVideoListSyncDataController : AWEListDataController
{
}

@end

@interface TikTokSearchVideoVerticalCustomFlowLayoutRowInfo : NSObject
{
}

@end

@interface TikTokSearchVideoVerticalCustomFlowLayout : UICollectionViewFlowLayout
{
}

@end

@interface TTKAutoPlayRuleActiveModel : NSObject
{
}

@end

@interface TTKCollectionViewSkeletonAnimationControl : TTKViewSkeletonAnimationControl
{
}

@end

@interface TTKDividingLineCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKDividingLineCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKDoubleColumnGeneralSearchCommonCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKDoubleColumnGeneralSearchCommonCollectionViewCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKDoubleColumnGeneralSearchMusicCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKDynamicBulletLynxCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKDynamicSparkLynxCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKFeedbackGuideInteractionView : UIView
{
}

@end

@interface TTKFeedbackManager : NSObject
{
}

@end

@interface TTKFeedbackView : UIView
{
}

@end

@interface TTKFeedSearchVideoCellAdaper : TTKSearchCardAdapter
{
}

@end

@interface TTKGeneralSearchSkeletonView : UIView
{
}

@end

@interface TTKGeneralSearchViewController : AWESearchBaseViewController
{
}

@end

@interface TTKJsonPatchManager : NSObject
{
}

@end

@interface TTKJsonPatchInfo : NSObject
{
}

@end

@interface TTKLiveVerticalSearchViewController : TTKVerticalSparkSearchViewController
{
}

@end

@interface TTKLynxContainerViewController : UIViewController
{
}

@end

@interface TTKOtherFeedbackView : UIView
{
}

@end

@interface TTKPoplayer : NSObject
{
}

@end

@interface TTKPoplayerMiddleParamsModel : TTKPoplayerParamsModel
{
}

@end

@interface TTKPoplayerParamsModel : NSObject
{
}

@end

@interface TTKPoplayerPresentationAnimator : NSObject
{
}

@end

@interface TTKPoplayerPresentationDelegate : NSObject
{
}

@end

@interface TTKPoplayerSearchCompletionParamsModel : TTKPoplayerParamsModel
{
}

@end

@interface TTKSearchAccessibleCollectionView : UICollectionView
{
}

@end

@interface TTKSearchAudioPlayerService : TTKSearchService
{
}

@end

@interface TTKSearchBarActionInfoManager : NSObject
{
}

@end

@interface TTKSearchBundleActivator : NSObject
{
}

@end

@interface TTKSearchCardAdapter : NSObject
{
}

@end

@interface TTKSearchCardManager : NSObject
{
}

@end

@interface TTKSearchCommonCardContext : NSObject
{
}

@end

@interface TTKSearchCommonCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKSearchContainerAutoPlayService : TTKSearchService
{
}

@end

@interface TTKSearchContainerListService : TTKSearchService
{
}

@end

@interface TTKSearchContainerSectionController : IGListSectionController
{
}

@end

@interface TTKSearchContainerService : TTKSearchService
{
}

@end

@interface TTKSearchContainerThemeService : TTKSearchService
{
}

@end

@interface TTKSearchContainerTrackerService : TTKSearchService
{
}

@end

@interface TTKSearchContainerTransitionService : TTKSearchService
{
}

@end

@interface TTKSearchContext : NSObject
{
}

@end

@interface TTKSearchFailureManager : NSObject
{
}

@end

@interface TTKSearchFilterCollectionViewFlowLayout : UICollectionViewFlowLayout
{
}

@end

@interface TTKSearchFilterCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKSearchFilterCollectionViewTableViewCell : UITableViewCell
{
}

@end

@interface TTKSearchFrequencyControlModel : NSObject
{
}

@end

@interface TTKSearchHorizentalLiveCell : UICollectionViewCell
{
}

@end

@interface TTKSearchHorizentalLiveCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKSearchHorizentalLiveViewModel : NSObject
{
}

@end

@interface TTKSearchHorizontalCollectionLiveView : TTKSearchHorizontalLivePlayBaseView
{
}

@end

@interface TTKSearchHorizontalLivePlayBaseView : UIView
{
}

@end

@interface TTKSearchHorizontalLoadMoreAdditionView : UIView
{
}

@end

@interface TTKSearchHorizontalLoadMoreControl : NSObject
{
}

@end

@interface TTKSearchHorizontalLynxView : UIView
{
}

@end

@interface TTKSearchHorizontalPlayRule : NSObject
{
}

@end

@interface TTKSearchHorizontalView : UIView
{
}

@end

@interface TTKSearchHorizontalViewCell : UICollectionViewCell
{
}

@end

@interface TTKSearchHotSpotAutoPlayCollectionViewCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKSearchImageRecommendCollectionViewCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKSearchLiveConfig : NSObject
{
}

@end

@interface TTKSearchLivePlayControllerManager : NSObject
{
}

@end

@interface TTKSearchLivePlayView : UIView
{
}

@end

@interface TTKSearchLiveView : UIView
{
}

@end

@interface TTKSearchLynxAwemeModelIndex : AWEBaseApiModel
{
}

@end

@interface TTKSearchLynxBounceView : LynxUIView
{
}

@end

@interface TTKSearchLynxElementBridge : NSObject
{
}

@end

@interface TTKSearchLynxElement : NSObject
{
}

@end

@interface TTKSearchLynxElementManager : NSObject
{
}

@end

@interface TTKSearchLynxHorizontalElement : LynxUI
{
}

@end

@interface TTKSearchLynxLiveElement : LynxUI
{
}

@end

@interface TTKSearchLynxVideoElement : LynxUI
{
}

@end

@interface TTKResourcePreLoad : NSObject
{
}

@end

@interface TTKSearchMaskPoplayer : NSObject
{
}

@end

@interface TTKSearchMessageCenter : NSObject
{
}

@end

@interface TTKSearchMessageModel : NSObject
{
}

@end

@interface TTKSearchNewLiveView : UIView
{
}

@end

@interface TTKSearchPerfBlockManager : NSObject
{
}

@end

@interface TTKSearchPlaceholderAccountCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKSearchPlaceholderMostVisitedTableViewCell : UITableViewCell
{
}

@end

@interface TTKSearchPlaceholderTrendingCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKSearchPlaceholderTrendingTableViewCell : UITableViewCell
{
}

@end

@interface TTKSearchPoplayer : NSObject
{
}

@end

@interface TTKSearchPreciseAdAutoPlayCollectionViewCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKSearchRecommendCollectionViewCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKSearchRichSugSectionHeader : UIView
{
}

@end

@interface TTKSearchRichUserSugTableViewCell : UITableViewCell
{
}

@end

@interface TTKSearchService : NSObject
{
}

@end

@interface TTKSearchServiceManager : NSObject
{
}

@end

@interface TTKSearchShopProductCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKSearchShopProductListView : UIView
{
}

@end

@interface TTKSearchSingleAutoPlayHotZoneRule : NSObject
{
}

@end

@interface TTKSearchSkeletonCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKSearchSkeletonTableViewCell : UITableViewCell
{
}

@end

@interface TTKSearchSparkCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKSearchSparkContainerViewController : UIViewController
{
}

@end

@interface TTKSearchSurveyDetailModel : AWEBaseApiModel
{
}

@end

@interface TTKSearchSurveyDataController : NSObject
{
}

@end

@interface TTKSearchSurveyViewController : UIViewController
{
}

@end

@interface TTKSearchThemeColorManager : NSObject
{
}

@end

@interface TTKSearchTimeManager : NSObject
{
}

@end

@interface TTKSearchTrackParamsHandlerRegister : NSObject
{
}

@end

@interface TTKSearchTrendingInflowDataController : AWEListDataController
{
}

@end

@interface TTKSearchUserCardViewModel : NSObject
{
}

@end

@interface TTKSearchUserTabContainerView : UIView
{
}

@end

@interface TTKSearchVideoCellInteractionView : UIView
{
}

@end

@interface TTKSearchVideoCSCell : UICollectionViewCell
{
}

@end

@interface TTKSearchVideoCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKSearchVideoCollectionViewCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKSearchVideoView : UIView
{
}

@end

@interface TTKSearchViewDelegateProxy : NSProxy
{
}

@end

@interface TTKShopVerticalSearchViewController : TTKVerticalSearchViewController
{
}

@end

@interface TTKSoundVerticalSearchViewController : TTKVerticalSearchViewController
{
}

@end

@interface TTKTableViewSkeletonAnimationControl : TTKViewSkeletonAnimationControl
{
}

@end

@interface TTKTrendingBillboardManager : NSObject
{
}

@end

@interface TTKUserSearchCollectionViewCell : UICollectionViewCell
{
}

@end

@interface TTKUserSearchCollectionViewCellAdapter : TTKSearchCardAdapter
{
}

@end

@interface TTKVerticalRespondModel : AWEBaseApiModel
{
}

@end

@interface TTKVerticalSearchViewController : AWESearchBaseViewController
{
}

@end

@interface TTKVerticalSparkSearchViewController : AWESearchBaseViewController
{
}

@end

@interface TTKViewSkeletonAnimationControl : NSObject
{
}

@end

@interface NSObject (TTKSearchRank)
@property(nonatomic) long long yy_searchRank;
@property(retain, nonatomic) NSNumber *ttk_searchMonitorIsFinished;
- (id)awe_searchMonitorContext;
@end

@interface AWEDynamicPatchModel (SyncDataSource) <TikTokSearchAladdinVideoListDataSourceHolder>
@property(retain, nonatomic) TikTokSearchVideoListSyncDataController *awe_syncDataController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

@interface AWEGeneralFilmTelevisionCardModel (AWESearch)
- (id)centerColor;
- (id)bgColor;
@end

@interface AWEGeneralFilmTelevisionTagModel (AWESearch)
- (id)tagWordColor;
@end

@interface AWEGeneralSearchModel (IGListDiffable) <IGListDiffable>
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
@property(retain, nonatomic) TikTokClickSugModel *ttk_clickSugModel;
@end

@interface AWEIndividualWordModel (IrregularWordProtocol) <AWEIrregularWordProtocol, AWERegularWordProtocol>
- (id)getQueryType;
- (unsigned long long)getTagType;
- (id)getImageURL;
- (id)getWordID;
- (long long)defaultStyle;
- (id)getContentString;
- (id)getSearchWord;
- (id)getDisplayWord;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSAttributedString *pureTextContent;
@property(readonly) Class superclass;
@end

@interface AWELynxContainer (InitialData)
@property(nonatomic) _Bool awe_initialDataLoaded;
@end

@interface AWEMusicModel (IGListDiffable) <IGListDiffable>
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
@property(retain, nonatomic) NSNumber *chunkDebugNumber;
@end

@interface AWESearchChallengeModel (IGListDiffable) <IGListDiffable, TikTokSearchAladdinVideoListDataSourceHolder>
@property(retain, nonatomic) NSNumber *chunkDebugNumber;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
@property(retain, nonatomic) TikTokSearchVideoListSyncDataController *awe_syncDataController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

@interface AWESearchMoreCardModel (IrregularWord) <AWEIrregularWordProtocol>
- (id)getSearchWord;
- (id)getDisplayWord;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSAttributedString *pureTextContent;
@property(readonly) Class superclass;
@end

@interface AWESearchUser (IGListDiffable) <IGListDiffable, TikTokSearchAladdinVideoListDataSourceHolder>
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
@property(retain, nonatomic) TikTokSearchVideoListSyncDataController *awe_syncDataController;
@property(retain, nonatomic) TikTokSearchPlaylistDataManager *tt_playlistDataManager;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

@interface AWEStorage (AWESearch)
+ (id)searchStorage;
@end

@interface AWEUIColor (TTKSearchDarkMode)
+ (id)colorNamed:(id)arg1 forceDarkMode:(_Bool)arg2;
+ (id)searchThemeColorNamed:(id)arg1 inTheme:(long long)arg2;
@end

@interface AWEUILoading (Search) <AWEUILoadingSearchProtocol>
+ (id)showSearchLoadingWithBackgroundOnView:(id)arg1;
+ (void)dismissSearchLoadingWithAnimated:(_Bool)arg1;
+ (void)dismissSearchLoading;
+ (id)showSearchLoadingWithBackground:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

@interface IGListSectionController (DoubleColumn) <IGListSupplementaryViewSource>
- (struct CGSize)sizeForSupplementaryViewOfKind:(id)arg1 atIndex:(long long)arg2;
- (id)viewForSupplementaryElementOfKind:(id)arg1 atIndex:(long long)arg2;
- (id)supportedElementKinds;
@property(retain, nonatomic) UIView *headerView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

@interface NSArray (AWESearchNilInfo)
@property(readonly, nonatomic) _Bool awe_emptyListHitCoreTable;
@property(retain, nonatomic) AWESearchNilInfoModel *awe_searchListNilInfo;
@end

@interface NSString (IrregularWord) <AWEIrregularWordProtocol>
- (id)getSearchWord;
- (id)getDisplayWord;
- (id)p_routerKeywordEncodingCharacterSet;
- (id)search_decodeURIComponent;
- (id)search_encodeURIComponent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSAttributedString *pureTextContent;
@property(readonly) Class superclass;
@end

@interface TikTokBillboardInfoModel (Placeholder)
@property(nonatomic) double cellHeight;

// Remaining properties
@property(nonatomic) _Bool hasShow;
@end

@interface AWEAwemeModel (SearchVideoCell)
@property(retain, nonatomic) YYTextLayout *ttk_descLayout;
@end

@interface UIColor (SearchUtil)
+ (id)awe_colorWithHexString:(id)arg1;
+ (id)aweSearch_colorWithARGBHexString:(id)arg1 defaultColor:(id)arg2;
+ (id)aweSearch_colorWithARGBHexString:(id)arg1;
@end

@interface UIImage (AWESearch)
+ (id)awe_searchImageNamed:(id)arg1;
@end

@interface UINavigationController (TTKTransitionFix)
+ (void)_aweLazyRegisterLoadWhenDylibLoad_TTKTransitionFix;
- (void)tt_setViewControllers:(id)arg1;
- (void)tt_setViewControllers:(id)arg1 animated:(_Bool)arg2;
@end

@interface UITableView (TTKSkeletonAnimationControl)
- (void)ttk_stopSkeletonAnimation;
- (void)ttk_startSkeletonAnimation;
@property(retain, nonatomic) TTKTableViewSkeletonAnimationControl *ttk_skeletonAnimationControl;
@end

@interface UICollectionView (TTKSkeletonAnimationControl)
- (void)ttk_stopSkeletonAnimation;
- (void)ttk_startSkeletonAnimation;
@property(retain, nonatomic) TTKCollectionViewSkeletonAnimationControl *ttk_skeletonAnimationControl;
@end

@interface UIViewController (MultiFeedFallThrough)
@property(nonatomic) long long searchMultiFeed_awemeIndex;
@property(nonatomic) long long searchMultiFeed_isEnterFeed;
@end

